# Generated by Django 2.0.6 on 2018-07-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name_plural': 'departamentos'},
        ),
    ]
