# Generated by Django 2.0.7 on 2018-07-10 15:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0004_auto_20180710_0939'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=datetime.datetime(2018, 7, 10, 15, 39, 11, 296562, tzinfo=utc), verbose_name='fecha de prestamos')),
                ('fecha_devolucion', models.DateField(default=datetime.datetime(2018, 7, 18, 15, 39, 11, 296562, tzinfo=utc), verbose_name='fecha de devolucion')),
                ('estado', models.PositiveSmallIntegerField(default=1)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Libros')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
