# Generated by Django 2.0.7 on 2018-07-10 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_auto_20180710_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='token',
            field=models.CharField(default='U4E9Z8SZRWC73GA', max_length=50),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(default=datetime.datetime(2018, 7, 18, 15, 49, 53, 322671, tzinfo=utc), verbose_name='fecha de devolucion'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(default=datetime.datetime(2018, 7, 10, 15, 49, 53, 322671, tzinfo=utc), verbose_name='fecha de prestamos'),
        ),
    ]
