# Generated by Django 2.0.7 on 2018-08-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0023_auto_20180727_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_devolucion',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_prestamo',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='token',
            field=models.CharField(default='YKF3UMCQDRHEKWH', max_length=50, unique=True),
        ),
    ]
