# Generated by Django 2.0.7 on 2018-08-02 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0026_auto_20180802_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(default=datetime.datetime(2018, 8, 2, 9, 19, 12, 203870), verbose_name='fecha de prestamos'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(default=datetime.datetime(2018, 8, 10, 9, 19, 12, 203870), verbose_name='fecha de devolucion'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='token',
            field=models.CharField(default='PGVWD5ZGCRU87DQ', max_length=50, unique=True),
        ),
    ]
