# Generated by Django 2.0.7 on 2018-07-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0004_auto_20180705_1130'),
        ('temas', '0006_auto_20180705_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='titulo')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='ubicacion')),
                ('disponibles', models.PositiveIntegerField(default=1, verbose_name='libros disponibles')),
                ('fecha_registro', models.DateField(auto_now=True, verbose_name='Fecha de ingreso')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autores.Author')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temas.Temas')),
            ],
            options={
                'verbose_name_plural': 'Libros',
                'ordering': ['id'],
            },
        ),
    ]
