# Generated by Django 2.0.7 on 2018-07-05 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 5, 17, 41, 0, 438293, tzinfo=utc), verbose_name='Fecha de ingreso'),
        ),
    ]
