# Generated by Django 2.0.7 on 2018-07-10 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_auto_20180709_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 10, 15, 39, 11, 295093, tzinfo=utc), verbose_name='Fecha de ingreso'),
        ),
    ]
