# Generated by Django 2.0.7 on 2018-07-10 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_auto_20180710_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 10, 18, 28, 32, 459280, tzinfo=utc), verbose_name='Fecha de ingreso'),
        ),
    ]
