# Generated by Django 2.0.6 on 2018-07-11 04:30

import apps.libros.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_auto_20180710_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='disponibles',
            field=models.PositiveIntegerField(default=1, validators=[apps.libros.validators.limit], verbose_name='libros disponibles'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 11, 4, 30, 0, 233175, tzinfo=utc), verbose_name='Fecha de ingreso'),
        ),
    ]
