# Generated by Django 2.0.6 on 2018-07-11 04:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_auto_20180710_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 11, 4, 48, 15, 229256, tzinfo=utc), verbose_name='Fecha de ingreso'),
        ),
    ]
