# Generated by Django 2.0.6 on 2018-07-13 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0014_auto_20180712_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 13, 18, 26, 57, 830563, tzinfo=utc), verbose_name='Fecha de ingreso'),
        ),
    ]
