# Generated by Django 2.0.7 on 2018-07-17 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0016_auto_20180717_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 17, 15, 59, 18, 734577, tzinfo=utc), verbose_name='Fecha de ingreso'),
        ),
    ]
