# Generated by Django 2.0.7 on 2018-07-17 16:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0017_auto_20180717_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=150)),
                ('latitud', models.CharField(max_length=300)),
                ('longitud', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Biblioteca',
                'verbose_name_plural': 'Bibliotecas',
            },
        ),
        migrations.AlterField(
            model_name='libros',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 17, 16, 11, 54, 430512, tzinfo=utc), verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='libros',
            name='biblioteca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='libros.Biblioteca'),
        ),
    ]
