# Generated by Django 2.0.6 on 2018-07-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='escolaridad',
            field=models.PositiveIntegerField(choices=[(1, 'None'), (2, 'Primaria'), (3, 'Basicos'), (4, 'Diversificado'), (5, 'Universidad'), (6, 'Maestria')], default=0, verbose_name='escolaridad'),
        ),
    ]
