# Generated by Django 2.0.7 on 2018-07-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0002_auto_20180702_1041'),
        ('usuarios', '0002_auto_20180702_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paises.Departamento'),
        ),
    ]
