# Generated by Django 2.0.7 on 2018-07-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_biblioteca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biblioteca',
        ),
    ]
