# Generated by Django 2.0.6 on 2018-07-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200, verbose_name='tema')),
                ('fecha_ingreso', models.DateField(auto_now=True, verbose_name='fecha_ingreso')),
            ],
        ),
    ]
