# Generated by Django 2.0.7 on 2018-07-07 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('temas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temas',
            options={'verbose_name_plural': 'Temas'},
        ),
        migrations.AlterField(
            model_name='temas',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2018, 7, 7, 16, 43, 47, 297585, tzinfo=utc), verbose_name='fecha_ingreso'),
        ),
    ]
