# Generated by Django 2.0.7 on 2018-07-12 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('temas', '0015_auto_20180712_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 16, 38, 53, 247061, tzinfo=utc), verbose_name='fecha_ingreso'),
        ),
    ]
