# Generated by Django 2.0.6 on 2018-07-13 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('temas', '0016_auto_20180712_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2018, 7, 13, 18, 26, 57, 814942, tzinfo=utc), verbose_name='fecha_ingreso'),
        ),
    ]
