# Generated by Django 2.0.7 on 2018-07-17 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('temas', '0017_auto_20180713_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2018, 7, 17, 15, 54, 59, 554699, tzinfo=utc), verbose_name='fecha_ingreso'),
        ),
    ]
