# Generated by Django 2.0.7 on 2018-07-17 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('temas', '0019_auto_20180717_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2018, 7, 17, 16, 11, 54, 426512, tzinfo=utc), verbose_name='fecha_ingreso'),
        ),
    ]
