# Generated by Django 2.0.7 on 2018-07-25 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('temas', '0020_auto_20180717_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime(2018, 7, 25, 17, 36, 54, 109384, tzinfo=utc), verbose_name='fecha_ingreso'),
        ),
    ]
