# Generated by Django 2.0.7 on 2018-07-04 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paises', '0002_auto_20180702_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='apellido')),
                ('genero', models.BooleanField(choices=[(True, 'masculino'), (False, 'femenino')], default=True, verbose_name='genero')),
                ('nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('fallecimiento', models.DateField(blank=True, null=True, verbose_name='fecha de fallecimiento')),
                ('fecha_registro', models.DateField(default=datetime.datetime(2018, 7, 4, 22, 16, 8, 391193, tzinfo=utc), verbose_name='fecha de registro')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paises.Pais')),
            ],
        ),
    ]
