# Generated by Django 2.0.7 on 2018-07-04 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 4, 22, 24, 18, 620012, tzinfo=utc), verbose_name='fecha de registro'),
        ),
    ]
