# Generated by Django 2.0.7 on 2018-07-05 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0003_auto_20180704_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 5, 17, 30, 54, 698117, tzinfo=utc), verbose_name='fecha de registro'),
        ),
    ]
