# Generated by Django 2.0.7 on 2018-07-05 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0004_auto_20180705_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 5, 17, 41, 0, 437296, tzinfo=utc), verbose_name='fecha de registro'),
        ),
    ]
