# Generated by Django 2.0.7 on 2018-07-10 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0006_auto_20180709_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 10, 18, 23, 12, 18263, tzinfo=utc), verbose_name='fecha de registro'),
        ),
    ]
