# Generated by Django 2.0.7 on 2018-07-12 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0011_auto_20180712_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 9, 33, 14, 576680), verbose_name='fecha de registro'),
        ),
    ]
