# Generated by Django 2.0.7 on 2018-07-12 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0012_auto_20180712_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 12, 10, 30, 5, 678609), verbose_name='fecha de registro'),
        ),
    ]
