# Generated by Django 2.0.6 on 2018-07-13 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0014_auto_20180712_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 13, 12, 26, 57, 814942), verbose_name='fecha de registro'),
        ),
    ]
