# Generated by Django 2.0.7 on 2018-07-17 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0016_auto_20180717_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2018, 7, 17, 9, 59, 18, 734577), verbose_name='fecha de registro'),
        ),
    ]
